# Generated by Django 3.2 on 2023-05-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230527_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='year',
            field=models.SmallIntegerField(default=1990),
            preserve_default=False,
        ),
    ]
